name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    name: "${{ matrix.package }}"
    runs-on: ubuntu-latest
    environment: split
    strategy:
      fail-fast: false
      matrix:
#        package: ['grumphp-bom-task', 'grumphp-xliff-task', 'phpstan-git-files', 'rector-p']
        package: ['rector-p']
    steps:
      - uses: actions/checkout@v4
      - run: ./split.sh ${{ matrix.package }}
