name: Run grumphp with different versions
on: [push]
jobs:
  test:
    name: "php: ${{ matrix.php }} TYPO3: ${{ matrix.typo3 }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']
        typo3: [false, true]
    container:
      image: kanti/buildy:${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - run: git config --global --add safe.directory /__w/grumphp-config/grumphp-config
      - run: |
          composer install --no-progress --no-scripts -n \
          && mv phpstan-baseline-without-typo3.neon phpstan-baseline.neon
        if: ${{ ! matrix.typo3 }}

      - run: composer req saschaegerer/phpstan-typo3 ssch/typo3-rector --no-progress --no-scripts -n
        if: ${{ matrix.typo3 }}

      - run: ./vendor/bin/grumphp run
