name: grumphp

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: "php: ${{ matrix.php }} TYPO3: ${{ matrix.typo3 }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']
        typo3: [false, true]
    container:
      image: kanti/buildy:${{ matrix.php }}
    env:
      COMPOSER_ROOT_VERSION: dev-main
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory /__w/grumphp-config/grumphp-config
      - if: ${{ ! matrix.typo3 }}
        run: |
          composer install --no-progress --no-scripts -n \
          && mv phpstan-baseline-without-typo3.neon phpstan-baseline.neon
      - if: ${{ matrix.typo3 }}
        run: composer req saschaegerer/phpstan-typo3 ssch/typo3-rector --no-progress --no-scripts -n
      - run: ./vendor/bin/grumphp run --ansi

  test-packages:
    name: "${{ matrix.package }} php: ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ['grumphp-bom-task', 'grumphp-xliff-task', 'phpstan-git-files', 'rector-p']
        php: ['8.2', '8.3', '8.4']
    container:
      image: kanti/buildy:${{ matrix.php }}
    env:
      COMPOSER_ROOT_VERSION: dev-main
    defaults:
      run:
        working-directory: ./packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory /__w/grumphp-config/grumphp-config
      - run: composer install --no-progress --no-scripts -n
      - run: ./vendor/bin/grumphp run --ansi

  code-split:
    name: "Code Split ${{ matrix.package }}"
    needs:
      - test
      - test-packages
    if: ${{ ( startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' ) && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment: code split
    env:
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        package: ['grumphp-bom-task', 'grumphp-xliff-task', 'phpstan-git-files', 'rector-p']
    steps:
      - uses: actions/checkout@v4
      - run: ./split.sh ${{ matrix.package }}
